var yubikey = require('./yubikey.js');

// Replace with your Yubico API id and signature key
yubikey.apiId = 38600; // Required
yubikey.apiKey = 'wIj8qiZAXPRPjaZzBQIfuyjx33U='; // Optional, will add HMAC-SHA-1 signature in requests and verify signature in response when set


// TODO figure out way to accept generated OTP from yubikey via usb to this var
// and pass into the method

var otp = ''; // OTP generated by Yubikey


// TODO live inside of a request made via http

yubikey.verify(otp, function(isValid, message) {
   
   if(isValid) {
      console.log('The Yubikey OTP is valid.');
   } else {
      console.log(message);
   }
   
});
